<?php
/**
 * @file
 * home_page.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function home_page_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-lower-footer-menu_accessibilitysection-508:http://my.whs.mil/?id=80
  $menu_links['menu-lower-footer-menu_accessibilitysection-508:http://my.whs.mil/?id=80'] = array(
    'menu_name' => 'menu-lower-footer-menu',
    'link_path' => 'http://my.whs.mil/?id=80',
    'router_path' => '',
    'link_title' => 'Accessibility/Section 508',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'menu-lower-footer-menu_accessibilitysection-508:http://my.whs.mil/?id=80',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 15,
    'customized' => 1,
  );
  // Exported menu link: menu-lower-footer-menu_eeod:http://my.whs.mil/eeod/
  $menu_links['menu-lower-footer-menu_eeod:http://my.whs.mil/eeod/'] = array(
    'menu_name' => 'menu-lower-footer-menu',
    'link_path' => 'http://my.whs.mil/eeod/',
    'router_path' => '',
    'link_title' => 'EEOD',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'menu-lower-footer-menu_eeod:http://my.whs.mil/eeod/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-lower-footer-menu_external-links-disclaimer:http://my.whs.mil/disclaimer-for-external-links/
  $menu_links['menu-lower-footer-menu_external-links-disclaimer:http://my.whs.mil/disclaimer-for-external-links/'] = array(
    'menu_name' => 'menu-lower-footer-menu',
    'link_path' => 'http://my.whs.mil/disclaimer-for-external-links/',
    'router_path' => '',
    'link_title' => 'External Links Disclaimer',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'menu-lower-footer-menu_external-links-disclaimer:http://my.whs.mil/disclaimer-for-external-links/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 25,
    'customized' => 1,
  );
  // Exported menu link: menu-lower-footer-menu_foia:http://my.whs.mil/disclaimer-external?id=79
  $menu_links['menu-lower-footer-menu_foia:http://my.whs.mil/disclaimer-external?id=79'] = array(
    'menu_name' => 'menu-lower-footer-menu',
    'link_path' => 'http://my.whs.mil/disclaimer-external?id=79',
    'router_path' => '',
    'link_title' => 'FOIA',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'menu-lower-footer-menu_foia:http://my.whs.mil/disclaimer-external?id=79',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 10,
    'customized' => 1,
  );
  // Exported menu link: menu-lower-footer-menu_no-fear-act:http://my.whs.mil/eeod/NoFEARAct/
  $menu_links['menu-lower-footer-menu_no-fear-act:http://my.whs.mil/eeod/NoFEARAct/'] = array(
    'menu_name' => 'menu-lower-footer-menu',
    'link_path' => 'http://my.whs.mil/eeod/NoFEARAct/',
    'router_path' => '',
    'link_title' => 'No FEAR Act',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'menu-lower-footer-menu_no-fear-act:http://my.whs.mil/eeod/NoFEARAct/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 5,
    'customized' => 1,
  );
  // Exported menu link: menu-lower-footer-menu_privacy-and-security:http://my.whs.mil/privacy-amd-security/
  $menu_links['menu-lower-footer-menu_privacy-and-security:http://my.whs.mil/privacy-amd-security/'] = array(
    'menu_name' => 'menu-lower-footer-menu',
    'link_path' => 'http://my.whs.mil/privacy-amd-security/',
    'router_path' => '',
    'link_title' => 'Privacy and Security',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'menu-lower-footer-menu_privacy-and-security:http://my.whs.mil/privacy-amd-security/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 20,
    'customized' => 1,
  );
  // Exported menu link: menu-top-footer-menu_dam:http://www.whs.mil/disclaimer-external?id=82
  $menu_links['menu-top-footer-menu_dam:http://www.whs.mil/disclaimer-external?id=82'] = array(
    'menu_name' => 'menu-top-footer-menu',
    'link_path' => 'http://www.whs.mil/disclaimer-external?id=82',
    'router_path' => '',
    'link_title' => 'DA&M',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'menu-top-footer-menu_dam:http://www.whs.mil/disclaimer-external?id=82',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 5,
    'customized' => 1,
  );
  // Exported menu link: menu-top-footer-menu_dod:http://www.whs.mil/disclaimer-external?id=77
  $menu_links['menu-top-footer-menu_dod:http://www.whs.mil/disclaimer-external?id=77'] = array(
    'menu_name' => 'menu-top-footer-menu',
    'link_path' => 'http://www.whs.mil/disclaimer-external?id=77',
    'router_path' => '',
    'link_title' => 'DoD',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'menu-top-footer-menu_dod:http://www.whs.mil/disclaimer-external?id=77',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 15,
    'customized' => 1,
  );
  // Exported menu link: menu-top-footer-menu_feedback:<front>
  $menu_links['menu-top-footer-menu_feedback:<front>'] = array(
    'menu_name' => 'menu-top-footer-menu',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Feedback',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'menu-top-footer-menu_feedback:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-top-footer-menu_pfpa:http://www.whs.mil/disclaimer-external?id=76
  $menu_links['menu-top-footer-menu_pfpa:http://www.whs.mil/disclaimer-external?id=76'] = array(
    'menu_name' => 'menu-top-footer-menu',
    'link_path' => 'http://www.whs.mil/disclaimer-external?id=76',
    'router_path' => '',
    'link_title' => 'PFPA',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'menu-top-footer-menu_pfpa:http://www.whs.mil/disclaimer-external?id=76',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 10,
    'customized' => 1,
  );
  // Exported menu link: menu-top-footer-menu_usagov:http://www.whs.mil/disclaimer-external?id=80
  $menu_links['menu-top-footer-menu_usagov:http://www.whs.mil/disclaimer-external?id=80'] = array(
    'menu_name' => 'menu-top-footer-menu',
    'link_path' => 'http://www.whs.mil/disclaimer-external?id=80',
    'router_path' => '',
    'link_title' => 'USA.gov',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'menu-top-footer-menu_usagov:http://www.whs.mil/disclaimer-external?id=80',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 20,
    'customized' => 1,
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('Accessibility/Section 508');
  t('DA&M');
  t('DoD');
  t('EEOD');
  t('External Links Disclaimer');
  t('FOIA');
  t('Feedback');
  t('No FEAR Act');
  t('PFPA');
  t('Privacy and Security');
  t('USA.gov');


  return $menu_links;
}
