<?php


//***** SEE:  (block) "jquery general routines (right side nav)" for jquery routines controlling taxonomy toggling.


function whs_taxonomy_menu_block_info() {

  $blocks['taxonomy_menu'] = array(
    'info' => t('Taxonomy menu'),
  );


  return $blocks;
}



function whs_taxonomy_menu_block_view($delta = '') {
	//We don't do anything if there is no TID or VID in the URL.
	//VID only equals vocab landing page -- should show everything.
	if (isset($_REQUEST['tid'])) {

		$tid=$_REQUEST['tid'];
		//Service page is set when the client is looking at a Services page as opposed to a directorate page.
		$ServicePage=FALSE;
		$RightMenu=TRUE;
	}else{


		//Are we on a taxonomy program page (Services instead of Directorates)
		if (arg(0)=="taxonomy"){
			$RightMenu=TRUE;
			$tid=arg(2);
			$ServicePage=TRUE;
		}else{

			//Do nothing -- this is for tracking active TID in the vocab chain only	
			$RightMenu=FALSE;
		}
	}


	//We must also have a vocabulary to pull the entire tree
	if (isset($_REQUEST['vid'])) {
		$vid=$_REQUEST['vid'];
	}else{
		//We will always have a vid if we have a tid (see above).  Just have to load it if not provided.
		$term=taxonomy_term_load($tid);
		$vid=$term->vid;
	}

	//This is the the themed content returned from the block

	$cont="";

	$title="";

	//Display SERVICE title.  We may need to add a flag for different titles if we use this elsewhere (other than service menu)
	//To be actionable at all, the item must be located in the same location as the user.  Location is set (a) from the user profile, or
	//(b) from the menu bar.  The function get_current_location() is defined in custom.module.
	$current_location=strtoupper(get_current_location());

	$title.='<div class="service-menu">';

	 if ($tid!=""){ $Term=taxonomy_term_load($tid);}else{$Term=taxonomy_vocabulary_load($vid);}

	  $menu_name=$Term->name;

	  $menu_name=strtoupper($menu_name);

	  //Updated in Nov 2015 per team discussion.  SRH
	  $title.="Related Programs (".$current_location.")";

	  //$title.=$menu_name;

	$title.='</div >';

  	$block = array();

  	// Taxonomy menu block.

  	if ($delta == 'taxonomy_menu') {

    		$terms = taxonomy_get_tree($vid); // Use the correct vocabulary id.

        	// Get the active trail tid-s.

	    	$active = $tid;
	    	$active_parents = taxonomy_get_parents_all($active);
    		$active_parents_tids = array();
    		foreach ($active_parents as $parent) {
      		$active_parents_tids[] = $parent->tid;

    	}
    


    // Build the menu.
    $term_count = count($terms);
    $cont = '<ul class="taxonomy_menu">';


    for ($i = 0; $i < $term_count; $i++) {

	$temp=taxonomy_term_load($terms[$i]->tid);
	$term_location=strtoupper($temp->field_service_location['und'][0]['value']);

	if ($term_location!=$current_location && $current_location!="ALL" && $term_location!="ALL") {
		//Skip to the next item if this one does not belong to the location we are presently in (ALL, Pentagon, Mark Center, etc.)
		continue;
	}

	$collapse_flag=FALSE;	
	$expand_flag=FALSE;

      	// Build the classes string.
      	$classes ='level-'.$i.' ';

	$lvl='level-'.$i;

      	$children = taxonomy_get_children($terms[$i]->tid);
      	$active_trail = in_array($terms[$i]->tid, $active_parents_tids);

      	if ($active_trail && $children){
	 	$classes .= 'expanded active-trail ';
	 	$expand_flag=TRUE;
	}elseif ($active_trail) { 
		$classes .= 'active-trail ';
      	}elseif ($children){
		 $classes .= 'collapsed ';
		 $collapse_flag=TRUE;
	}

      

	global $base_url;



	//If there are no children for this term...

   if ($i == 0){
	//$terms[$i]->depth
	$cont .= '<li class="first '.$classes.'">';

		if ($collapse_flag) {

			$cont.='<img class="collapsed_image" src="'.theme_path().'/images/menu-collapsed.gif" alt="bullet ">';

		}

		if ($expand_flag) {

			$cont.='<img class="collapsed_image" src="'.theme_path().'/images/menu-expanded.gif" alt="bullet ">';
		}
		if ($ServicePage!=TRUE) {
			$cont.='<a href="'.$base_url.'/home?vid='.$vid.'&tid='.$terms[$i]->tid.'&qt-whs_home_page_service_table=2">'.$terms[$i]->name.'</a>';
		}else{
			//$path=url($base_url."taxonomy/term/".$terms[$i]->tid);
			//$cont.='<a href="'.$path.'">'.$terms[$i]->name.'</a>';
			$cont.=l($terms[$i]->name,"taxonomy/term/".$terms[$i]->tid);
		}
   } else {

        if ($terms[$i]->depth == $depth){ 
		$cont .= '</li><li class="'.$classes.'">';
		if ($collapse_flag) {
			$cont.='<img class="collapsed_image" src="'.theme_path().'/images/menu-collapsed.gif" alt="bullet ">';
		}

		if ($expand_flag) {
			$cont.='<img class="collapsed_image" src="'.theme_path().'/images/menu-expanded.gif" alt="bullet ">';
		}

		if ($ServicePage!=TRUE) {
			$cont.='<a href="'.$base_url.'/home?vid='.$vid.'&tid='.$terms[$i]->tid.'&qt-whs_home_page_service_table=2">'.$terms[$i]->name.'</a>';
		}else{
			//$path=url($base_url."taxonomy/term/".$terms[$i]->tid);
			//$cont.='<a href="'.$path.'">'.$terms[$i]->name.'</a>';
			$cont.=l($terms[$i]->name,"taxonomy/term/".$terms[$i]->tid);
		}

	}elseif ($terms[$i]->depth > $depth) {

		$cont .= '<ul class="tier-'.$terms[$i]->depth.'"><li class="first '.$classes.'">';

		if ($collapse_flag) {
			$cont.='<img class="collapsed_image" src="'.theme_path().'/images/menu-collapsed.gif" alt="bullet ">';
		}

		if ($expand_flag) {
			$cont.='<img class="collapsed_image" src="'.theme_path().'/images/menu-expanded.gif" alt="bullet ">';
		}

		if ($ServicePage!=TRUE) {
			$cont.='<a href="'.$base_url.'/home?vid='.$vid.'&tid='.$terms[$i]->tid.'&qt-whs_home_page_service_table=2">'.$terms[$i]->name.'</a>';
		}else{
			//$path=url($base_url."taxonomy/term/".$terms[$i]->tid);
			//$cont.='<a href="'.$path.'">'.$terms[$i]->name.'</a>';
			$cont.=l($terms[$i]->name,"taxonomy/term/".$terms[$i]->tid);
		}

        }elseif ($terms[$i]->depth < $depth) {

          // Add missing end-tags depending of depth level difference.

          for ($j = $terms[$i]->depth; $j < $depth; $j++) {

            $cont .= '</li></ul>';

          }

          //$cont .= '</li><li id="'.$lvl.'" class="'.$classes.'" onclick="document.getElementById(\''.$lvl.'\').classList.toggle(\'collapsed\')">';
          $cont .= '</li><li id="'.$lvl.'" class="'.$classes.'">';
		if ($collapse_flag) {
			$cont.='<img class="collapsed_image" src="'.theme_path().'/images/menu-collapsed.gif" alt="bullet ">';
		}

		if ($expand_flag) {
			$cont.='<img class="collapsed_image" src="'.theme_path().'/images/menu-expanded.gif" alt="bullet ">';
		}

		if ($ServicePage!=TRUE) {
			$cont.='<a href="'.$base_url.'/home?vid='.$vid.'&tid='.$terms[$i]->tid.'&qt-whs_home_page_service_table=2">'.$terms[$i]->name.'</a>';
		}else{
			//$path=url($base_url."taxonomy/term/".$terms[$i]->tid);
			//$cont.='<a href="'.$path.'">'.$terms[$i]->name.'</a>';
			$cont.=l($terms[$i]->name,"taxonomy/term/".$terms[$i]->tid);
		}
        }

  

      // If we have reached the last element add all possibly missing end-tags.

        if (!isset($terms[$i+1])) {

          for ($j = 0; $j < $terms[$i]->depth; $j++) {

            $cont .= '</li></ul>';

          }

        }

      }

      $depth = $terms[$i]->depth;

    }



    $cont .= '</li></ul>';

    

    // Set the menu html as block content.



	//Is this block being used for the right service nav or the center WHS category nav?

	if ($RightMenu){

		$div="taxonomy_menu_wrapper";

	}else{

		$div="taxonomy_category_wrapper";

	}

    $block['content'] = array('#markup' => '<div class="'.$div.'">'.$title.$cont.'</div>');

  }

  

  return $block;

}

?>