<?php





//SRH  Re-written code to obtain OPM Status

//Feb 2015

function getOPMStatus(){



	try{

		//Get data from the OPM feed.

		$opm =simplexml_load_file("http://www.opm.gov/xml/operatingstatus.xml");

		
		if (!$opm) {
			//If the OPM site is too busy to return a value, default to OPEN
			$icon="open";
			$status="Open";
		}else{
			$icon=strtolower($opm->Icon);
			if ($icon=="") {$icon="open";}
			$status=$opm->StatusType;
			$status="";
		}
			

		$html="";



		$html = '<div class="opm">';


		//This needs to be dynamic to account for the various environments.

		$WhichPath=drupal_get_path('module','opm');
		global $base_path;

		$html .= '<span class="opm_icon">OPM Status<br><a href="http://www.opm.gov/policy-data-oversight/snow-dismissal-procedures/current-status/" title="OPM Current Status">

			<img class="left" src="'.$base_path.$WhichPath.'/images/opm-' . $icon. '.png" 

			height="30" width="30" alt="OPM Status">

			';



		$html .= '<span class="status">' . $status. '</span></a>';



		$html .= '</div>';



	}



	catch(Exception $e)



	{



		watchdog("opm","getOPMStatus " . $e->getMessage());



	}



	



	return $html;



}





?>